---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 130.193.49.85
    jenkins-agent-01:
      ansible_host: 158.160.41.196
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: gaidar
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'