---
- name: Preapre all hosts
  hosts: all
  become: true
  tasks:
    - name: Create group
      group:
        name: "{{ user_group }}"
        state: present
    - name: Create user
      user:
        name: "{{ user_name }}"
        generate_ssh_key: true
      register: ssh_key_info
    
    - name: Install JDK11
      become: true
      package:
        name: "{{ java_packages }}"
        state: present

    - name: Get JDK17
      get_url:
        url: "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.6%2B10/OpenJDK17U-jdk_x64_linux_hotspot_17.0.6_10.tar.gz"
        dest: "/tmp"

    - name: Extract JDK17
      unarchive:
        src: "/tmp/OpenJDK17U-jdk_x64_linux_hotspot_17.0.6_10.tar.gz"
        dest: "/opt"
        remote_src: true

    - name: Create symbolic link for JDK17
      file:
        src: /opt/jdk-17.0.6+10/bin/java
        dest: /usr/bin/java
        state: link
        force: yes

- name: Get Jenkins master installed
  become: true
  hosts: jenkins_masters
  tasks:
    - name: Get repo Jenkins
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        validate_certs: false
    - name: Add Jenkins key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
        validate_certs: false
    - name: Install epel-release
      yum:
        name: epel-release
        state: present
    - name: Install Jenkins and requirements
      yum:
        name:
          - jenkins
          - git
        state: present
      register: jenkins_installed
    - name: Ensure jenkins agents are present in known_hosts file
      become_user: "{{ jenkins_user_name }}"
      known_hosts:
        name: "{{ hostvars[item].ansible_host }}"
        state: present
        key: "{{ lookup('pipe', 'ssh-keyscan {{ hostvars[item].ansible_host }}') }}"
        hash_host: true
      with_items: "{{ groups.jenkins_agents }}"
    - name: Start Jenkins
      systemd:
        name: jenkins
        state: restarted
        enabled: true
      when: jenkins_installed is changed
- name: Prepare jenkins agent
  hosts: jenkins_agents
  become: true
  become_user: "{{ jenkins_user_name }}"
  tasks:
    - name: Add master publickey into authorized_key
      authorized_key:
        user: "{{ jenkins_user_name }}"
        state: present
        key: "{{ hostvars['jenkins-master-01']['ssh_key_info']['ssh_public_key'] }}"
    - name: Create agent_dir
      become_user: root
      file:
        path: "{{ jenkins_agent_dir }}"
        state: directory
        owner: "{{ jenkins_user_name }}"
        group: "{{ jenkins_user_group }}"
    - name: Add docker repo
      become_user: root
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        validate_certs: false
    - name: Install some required
      become_user: root
      yum:
        name:
          - git
          - python3
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
    - name: Update pip
      become_user: root
      pip:
        executable: pip3
        name: pip
        extra_args: --upgrade
    - name: Install Ansible
      become_user: root
      pip:
        executable: pip3
        name:
          - selinux
          - ansible<3.0
        state: present
    - name: Reinstall Selinux
      become_user: root
      pip:
        executable: pip3
        name:
          - selinux
        state: forcereinstall
    - name: Add local to PATH
      lineinfile:
        dest: ~/.bashrc
        regexp: export PATH=$PATH:/home/jenkins/.local/bin
        line: export PATH=$PATH:/home/jenkins/.local/bin
    - name: Create docker group
      become_user: root
      group:
        name: docker
        state: present
    - name: Add jenkinsuser to dockergroup
      become_user: root
      user:
        name: "{{ jenkins_user_name }}"
        groups: docker
    - name: Restart docker
      become_user: root
      systemd:
        name: docker
        state: restarted
        enabled: true
    - name: Install agent.jar
      get_url:
        url: "http://{{ hostvars['jenkins-master-01']['ansible_host'] }}:8080/jnlpJars/agent.jar"
        dest: "{{ jenkins_agent_dir }}"
      register: install_agent
      until: install_agent is succeeded
      retries: 10
      timeout: 10

